version: '3.8'

services:
  consul:
    image: hashicorp/consul
    container_name: consul-server
    restart: always
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui'
    networks:
      - fm-network

networks:
  fm-network:
    name: fm-network
