version: '3.8'

services:
  user-service:
    image: my-user-service
    container_name: user-service
    restart: always
    depends_on:
      - postgres
    networks:
      - fm-network
    env_file:
      - .env
    ports:
      - '5000:5000'
    command: >
      sh -c "node server.js"

  postgres:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      - POSTGRES_DB=${USER_DB_NAME}
      - POSTGRES_USER=${USER_DB_USER}
      - POSTGRES_PASSWORD=${USER_DB_PASS}
    networks:
      - fm-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

networks:
  fm-network:
    name: fm-network
